services:
  host:
    build: ./host
    ports:
      - "8080:8080"
    volumes:
      - ./host:/app
      - /app/node_modules

  auth:
    build: ./users
    ports:
      - "8081:8081"
    volumes:
      - ./auth:/app
      - /app/node_modules

  profile:
    build: ./tasks
    ports:
      - "8082:8082"
    volumes:
      - ./profile:/app
      - /app/node_modules

  places:
    build: ./tasks
    ports:
      - "8083:8083"
    volumes:
      - ./places:/app
      - /app/node_modules
